name: 'Docker Test'
description: 'Docker Test Images'
inputs:
  arch:
    description: 'Docker architecture'
    default: 'amd64'
  dockerDistro:
    description: 'Linux Distro'
    default: 'debian.12'
  dotnetVersion:
    description: '.net version'
    default: '8.0'

runs:
  using: 'composite'
  steps:
  -
    name: '[Docker Build & Test] DockerHub'
    shell: pwsh
    run: dotnet run/docker.dll --target=DockerTest --arch=${{ inputs.arch }} --dotnet_version=${{ inputs.dotnetVersion }} --docker_distro=${{ inputs.dockerDistro }} --docker_registry dockerhub --verbosity=diagnostic
  -
    name: '[Docker Build & Test] GitHub'
    shell: pwsh
    run: dotnet run/docker.dll --target=DockerTest --arch=${{ inputs.arch }} --dotnet_version=${{ inputs.dotnetVersion }} --docker_distro=${{ inputs.dockerDistro }} --docker_registry github --verbosity=diagnostic
