on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      arch:
        required: true
        type: string

env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  DOTNET_ROLL_FORWARD: "Major"
  
jobs:
  artifacts:
    name: ${{ matrix.dockerDistro }} - net${{ matrix.dotnetVersion }}
    runs-on: ${{ inputs.runner }}
    strategy:
      fail-fast: false
      matrix:
        dockerDistro:
          - alpine.3.20
          - centos.stream.9
          - debian.12
          - fedora.40
          - ubuntu.20.04
          - ubuntu.22.04
          - ubuntu.24.04
        dotnetVersion: [ '8.0', '6.0' ]

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: Restore State
      uses: ./.github/actions/cache-restore
    -
      uses: actions/download-artifact@v4
      name: Download nuget packages
      with:
        name: nuget
        path: ${{ github.workspace }}/artifacts/packages/nuget
    -
      uses: actions/download-artifact@v4
      name: Download native packages
      with:
        name: native-Linux
        path: ${{ github.workspace }}/artifacts/packages/native
    -
      name: '[Test Artifacts]'
      shell: pwsh
      run: dotnet run/artifacts.dll --target=ArtifactsTest --arch=${{ inputs.arch }} --dotnet_version=${{ matrix.dotnetVersion }} --docker_distro=${{ matrix.dockerDistro }}